name: Release

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "dev/**"
      - "dependabot/**"
      - "maven"
    paths-ignore:
      - "README.md"
      - '.gitignore'
      - "LICENSE*"
      - '.github/workflows/dependabot-auto-merge.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    uses: T2PeNBiX99wcoxKv3A4g/Release-Workflows/.github/workflows/jvm_release.yml@main
    with:
      publish_maven: true